Fix script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,9 +54,19 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           command_timeout: 15m
           script: |
+            if ! docker compose version > /dev/null 2>&1; then
+              echo "Docker Compose not found. Installing..."
+              sudo dnf install -y dnf-plugins-core
+              sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
+              sudo dnf install -y docker-compose-plugin
+            fi
+            
+            mkdir -p ~/app
             cd ~/app
             
             echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
+            
+            docker rm -f cv-shivam || true
             
             IMAGE_NAME=${{ env.IMAGE_NAME }} docker compose pull
             IMAGE_NAME=${{ env.IMAGE_NAME }} docker compose up -d --remove-orphans
